### ISSUE TITLE
[Feature request] Allow setting reverse DNS on ip

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#116]
This needs an API first since the [network interfaces creation API](http://doc.rpc.gandi.net/hosting/reference_iface.html#IfaceDescription) don't seem to have the _reverse_ parameter.

Being able to set it at VM creation would be great!

**Comment by sayoun** [comment]
Indeed we should do it, meanwhile with release 0.13 you can use `gandi ip update --reverse` to update the reverse

**Comment by rdoursenaud** [comment]
Thanks! Will look into it.

**Comment by stissot** [comment]
This feature being now available in `gandi.cli`, I think we can close the issue.

**Comment by rdoursenaud** [comment]
Thanks for the heads up @stissot.
