### ISSUE TITLE
[Misfeature] Allow *not* ssh'ing after gandi vm create

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#118]
While automatically connecting to the vm may seem useful for some use cases, one may want to execute some more commands before connecting (eg. creating and attaching some disks, adding zone entries…).

The connection should be optional or a parameter exposed to disable the automatic connection.

**Comment by kalou** [comment]
True that. We have an internal changeset handling that:

add --ssh to vm create defaulting to False
add --wait to vm ssh

Can we have this merged ?

**Comment by sayoun** [comment]
This is now available in release 0.13, I'm closing this issue.
