### ISSUE TITLE
[Feature request] Allow passing parameters to --script

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#128]
gandi vm create allows to pass a script with --script.

Being also able to also pass parameters to that script would be very handy for automatic provisioning with pre-existing bootstrap scripts requiring parameters (amongst other use cases).

My use case: https://github.com/saltstack/salt-bootstrap

**Comment by kalou** [comment]
Agreed, been finding a moment to implement that.
This is split into three changes, one for the Gandi API, one for swapsetup.py and the last one for gandi.cli. I'll MR https://github.com/kalou/gandi.cli/commit/8cc19935426b08028d1464291b0b1aedccaed98e  once we have the change ack'ed into the API/backends.

I had difficulties chosing a proper way to specify arguments, ended up with --script_args="whatever the shell will split into an argv" for probably bad CLI/UX reasons.

**Comment by sayoun** [comment]
Fixed in 0.17 but need to have Gandi public API updated, should be done this week.
