### ISSUE TITLE
[Feature request] Ability to delete a list of IP addresses

### ISSUE THREAD

**Issue by themouette** [Gandi/gandi.cli#129]
I tried to delete a bunch of private IP addresses by running 

``` sh
gandi ip delete --force $(gandi ip list --detached | awk '/ip/ {print $3}')
```

and encounter the following error:

> Error: Got unexpected extra arguments (192.168.1.4 192.168.1.5 )

It would be great to be able to delete IP addresses by batch, don't you think ?

To bypass this limitation, I temporary use a bash `for` loop:

``` sh
for i in $(gandi ip list --detached | awk '/ip/ {print $3}') ; do gandi ip delete --force $i ; done
```

Here is my current configuration

```
$ uname -a
Linux XXXXX 3.14-2-amd64 #1 SMP Debian 3.14.15-2 (2014-08-09) x86_64 GNU/Linux

$ gandi --version
Gandi CLI 0.12

Copyright: © 2014-2015 Gandi S.A.S.
License: GPL-3
```

**Comment by sayoun** [comment]
Done in release 0.15
