### ISSUE TITLE
Add Debian packaging compliant with multi python version (2.x and 3.x)

### ISSUE THREAD

**Issue by aegiap** [Gandi/gandi.cli#139]
As the contributing documentation [1] suggest, I create a enhancement issue for the Debian packaging of the CLI with python3. See pull request #138 [2]

[1]: https://github.com/Gandi/gandi.cli/blob/master/CONTRIBUTING.md
[2]: https://github.com/Gandi/gandi.cli/pull/138

**Comment by sayoun** [comment]
The PR has been merged so I will close this issue
