### ISSUE TITLE
[Feature request] Add disk size modifiers

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#140]
The possibility to modify disk sizes without knowing their actual size would be great.

An implementation in fdisk fashion would be great.

Something like "gandi disk --resize **+1T** *RESOURCE*" (Add 1 TB to resource disk).

**Comment by sayoun** [comment]
Fixed in release 0.17

**Comment by rdoursenaud** [comment]
\o/
Thanks!
