### ISSUE TITLE
[Feature request] Don't limit scripts to 16384 characters

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#143]
Looks like the ```--script``` parameter of the ```gandi vm create``` command passes the file content as a string. But the API don't want it to be more than 16384 characters.

Got:
```
Error: Gandi API has returned an error: <Fault 501237: 'Error on object : OBJECT_STRING (CAUSE_BADPARAMETER) [script: string \'### REDACTED SCRIPT CONTENT ###\' has more than 16384 chars]'>
```

Is it possible to overcome this limit?

**Comment by kalou** [comment]
Hm given the dirty way we upload script to the API (xmlrpc value post) and how we hand it to the VM, I'd rather not extend this too much - having users getting used to this for now. Probably worth fixing when we have a more appropriate upload handling ?

**Comment by rdoursenaud** [comment]
Ok, back to scp then ;)

Thanks!
