### ISSUE TITLE
Update click install_requires to >= 4.0

### ISSUE THREAD

**Issue by koobs** [Gandi/gandi.cli#147]
Currently the dependency on click is set to <= 4.0, and click 4.1 has recently been released. click 4.1 is packaged in at least the FreeBSD operating system (ports).

While it is acknowledged that their may be valid reasons for doing this, eg: "any version up to but not including the next major or minor version for potential API compatibility", version requirements such as == and <= are restrictive and fail unsafely (breakages) when dependent packages are updated.

Production releases of Python software should stipulate and target more appropriate (and less restrictive) version requirements, such that updates to dependent packages does not break the software in question (gandi.cli).

In this case, gandi.cli should target and test (QA) click>=4.1 'by default', and only limit versions if they are made incompatible

**Comment by sayoun** [comment]
Hello,

indeed we restrict the version to be sure it doesn't break anything until we validate it, then we upgrade the click version dependency. I'll check that it works fine with 4.1 and then I will update the requirement in the next release.

**Comment by sayoun** [comment]
In next release 0.16, click requirement was bumped to <= 5.2

**Comment by koobs** [comment]
@sayoun I would propose the requirement be updated to >= 4.1 (ie; the min version supported), with the CI environment (Travis?) reconfigured to always build with the latest release version of click. This way upstream is always ahead of the curve, as it should be.

**Comment by sayoun** [comment]
@koobs You're right, I've updated the requirement to be `click>=3.1` as it's the minimum version needed, it will be in next release 0.16.

**Comment by koobs** [comment]
@sayoun Much appreciated :)

**Comment by sayoun** [comment]
Closing this issue as it's in release 0.16
