### ISSUE TITLE
Improve configuration and default values

### ISSUE THREAD

**Issue by ziir** [Gandi/gandi.cli#149]
Hello,

I've been thinking about how to improve the way Gandi CLI allows users to
get/set configuration and default values.

This is what I took into consideration:
- There is no gandi command to display current configuration and/or default values.
- There's no way to display single specific configuration and/or defaults values.
- Default values are overriden at every command

This is what I would suggest, freely inspired from NPM CLI :

- gandi config
  - gandi config set ```<key> <value>``` [-g]
  - gandi config get ```[<key>]``` [-g]
  - gandi config delete ```<key>```  [-g]
  - gandi config list  [-g]
  - gandi config edit  [-g]

- set a default value in config.yml only if the key is not present yet.

As per current behavior, -g should force use of global configuration for the given action.

I'm willing to open an MR and work on this.

What do you think?

Related to #91 and #54

**Comment by sayoun** [comment]
Seems good to me

**Comment by zaurky** [comment]
I don't think the alias part is a good idea, we don't have it anywhere else, and in all the other modules, we use delete and list (no rm nor ls).

**Comment by ziir** [comment]
@zaurky Ok, I understand and I'm willing to remove aliases from this issue's scope.
Do you think using aliases might be a good idea for Gandi CLI and I should create a separate issue though ?

**Comment by sayoun** [comment]
@ziir I think we should avoid having aliases in the CLI, we want to keep it simple (KISS): only one command for one action, no two differents commands for the same thing. You should remove it from the scope if this issue.

**Comment by ziir** [comment]
@sayoun Ok, done.

**Comment by kopax** [comment]
Hi, what is the format of a key? Is it the env name?

**Comment by sayoun** [comment]
@kopax the API key is a hash token and can be retrieved as explained in the README https://github.com/Gandi/gandi.cli/blob/master/README.md#getting-started . The env name is used only during setup to decide which API Host endpoint to use.
