### ISSUE TITLE
Test fails with Python 3.5

### ISSUE THREAD

**Issue by imrehg** [Gandi/gandi.cli#154]
Running the tests on Arch Linux with Python 3.5.0 (the default now), I get 4 errors of

    click.exceptions.UsageError: No such command "test".

Here's the complete output of the `python setup.py test`: https://gist.github.com/imrehg/6044fadb0383123c686e

I've tried Python 2.7.10 (the default python2 on Arch), that finishes the tests just fine.

Because of the tests failures the Arch package cannot be installed either (just for context).

I'm using the latest 0505e2dae7672bfbd02bfe4c2db69a139c2c2499 commit, and have `Linux nostromo 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

**Comment by sayoun** [comment]
Hello,

as specified in the Readme and setup.py, we only support python version 2.6/2.7/3.3/3.4.

I'll look into this but if you want to propose a patch it would be great :)

**Comment by imrehg** [comment]
I was checking it out, but not sure yet. Just bring it up since you have an Arch Linux package (in this repo) that is broken / can't be installed because of this. I'll submit a patch if I figure out what's going on.

**Comment by sayoun** [comment]
I've run tests with python3.5 using debian and it worked fine here https://gist.github.com/sayoun/1b7d805ad73917412e43

**Comment by romuald** [comment]
Looks like click interfering with the python setup.py test commandline

**Comment by imrehg** [comment]
I looked into it a bit more, and the trick is to not run

    python setup.py test

but instead the correct way with nose + setuptools is to run

    python setup.py nosetests

Doing that all seem to work. I did an update to the Arch package (see #155).

I guess the "test" part could be removed from the `setup.py` as well. A patch to tests is on the branch https://github.com/imrehg/gandi.cli/tree/154-fix-tests

**Comment by sayoun** [comment]
I've fixed the setup.py so the command `python setup.py test` will work now and use nose, it's in the 
commit 2a8b632287d1a8bf3ae421561f523dcc79245957 .

You should make a pull request for your Arch Linux package update, or you want to wait until next 0.17 release ?

**Comment by imrehg** [comment]
How will that work with tox as that runs `nosetests`, so is it noted in the docs how one should run the tests properly?

If this part is updated, then the Arch package should work again already. The other 2 changes included in #155 (besides this) are not very urgent, so can rewrite that patch and send it again without the "test" change.

So it should be a pull request? (your contribution guide is a bit confusing, does not seem to allow pull requests, hence the linking in the issue, I prefer pull requests in general too)

**Comment by sayoun** [comment]
Both `python setup.py test` and `python setup.py nosetests` commands work now, `tox` command to run tests still works too, and so is Travis running test suite.

Sorry if it's confusing for you, but the contribution guide clearly say that PR are welcome, which you can verify by the 88 already closed PR on this project.

I'm closing this issue now, as the main problem about tests not running in 3.5 has been fixed in the latest commit, which will be included in the next release 0.17.
