### ISSUE TITLE
Wrong list of sizes of the PaaS instance in command help

### ISSUE THREAD

**Issue by whitone** [Gandi/gandi.cli#156]
The command

    gandi paas create --help

gives the following options for *--size* parameter:

    --size [s|m|x|xl|xxl]           Size of the PaaS instance.

but

    gandi paas create --size x ...

gives the following error:

    Error: Gandi API has returned an error: <Fault 500037: 'Error on object : OBJECT_UNKNOWN (CAUSE_BADPARAMETER) [size: x not in list s,m,l,xl,xxl]'>

So I changed to:

    gandi paas create --size l ...

but other error:

    Error: Invalid value for "--size": invalid choice: l. (choose from s, m, x, xl, xxl)

**Comment by sayoun** [comment]
Thanks I'll look into this, do you use the latest CLI version ?

**Comment by sayoun** [comment]
This is fixed in commit 5587b9e75ea1ab32c766eaa4f0216c455eefd713.

You can use the latest code from the github repository until the next version 0.17 is released.

**Comment by whitone** [comment]
OK, thank you.

However I had the last version, with

    gandi --version

I get:

    Gandi CLI 0.16
