### ISSUE TITLE
the cli doesn't response

### ISSUE THREAD

**Issue by duub** [Gandi/gandi.cli#164]
I've run the gandi setup, introduced all the data it asks and when I try to execute a command it shows the help menu related to the options.

an example:
```
~> gandi paas console myvhost
paas clone    Clone a remote vhost in a local git...
paas console  Open a console on a PaaS.
paas create   Create a new PaaS instance and initialize...
paas delete   Delete a PaaS instance.
paas info     Display information about a PaaS instance.
paas list     List PaaS instances.
paas restart  Restart a PaaS instance.
paas types    List types PaaS instances.
paas update   Update a PaaS instance.
```

this are the os and gandi version:
```
~> uname -a
Linux cxiam 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
~> gandi --version
Gandi CLI 0.16

Copyright: © 2014-2015 Gandi S.A.S.
License: GPL-3
```

**Comment by rdoursenaud** [comment]
Can you check what version of python-click is installed? This looks like the behavior I'm getting with version 6.2 (see #165).

**Comment by sayoun** [comment]
I confirm that the current Gandi CLI doesn't work with click version > 6.0, it still works with version 5.x and below.
@duub Try to downgrade your python-click version is you can and test again to see it you still have the same issue please.

**Comment by sayoun** [comment]
Or you can try getting the latest version from the github master branch which should work now.

**Comment by duub** [comment]
I've decided to downgrade the click package to the latest 5.x version. It's strange because it's a fresh debian install so I don't know where I got the latest version...

thank you for your time and patience!
