### ISSUE TITLE
Compatiblity with click 6.x

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#165]
I know the currently supported version is ≤ 4.
But I'm an Arch Linux user so I live on the bleeding edge ;)
I also maintain the Arch Linux package.
Arch currently ships python-click at 6.2 and I can't be bothered to package and maintain python-click4 on the AUR.
Anyway, being compatible with the latest version would be nice.
At the moment, on my system running click 6.2, sub-subcommands do not work and issues the subcommand help instead.
Ex:
```
$ gandi record create example.com --type CNAME --value test2.example.com --name test
record create  Create new DNS zone record entry for a...
record delete  Delete a record entry for a domain
record list    List DNS zone records for a domain.
record update  Update records entries for a domain from a...
```
I'd gladly have made a pull request if I knew how to fix this but it wasn't obvious to me at first glance (I'm not familiar with click ATM). Someone more familiar with click and the codebase may have better luck, hence me opening this issue.

**Comment by sayoun** [comment]
I confirm that the current Gandi CLI doesn't work with click version > 6.0, it still works with version 5.x and below. I'll see what I can do.

**Comment by sayoun** [comment]
Commit https://github.com/Gandi/gandi.cli/commit/36e3b33bbc0a707ff8ff69e4a5e05922669ddd46 should fix the problem and make the CLI work with click 6.x 

I'm closing this issue and will try to make a new CLI release soon so the fix can be packaged.

**Comment by rdoursenaud** [comment]
Thanks!
Just tested it and it works ok \o/
Looking forward to the new release.
