### ISSUE TITLE
[Feature Request] Easy way to use multiple accounts

### ISSUE THREAD

**Issue by jake9050** [Gandi/gandi.cli#174]
Right now you register the cli client with one account, if you want to use pultiple accounts you can either:

- run setup again to register with another api key
- create multiple installs of the cli tools

Both are workarounds imo, it would be nice if there is a way to register multiple accounts and choose the one you want to use with a simple command; eg something like

`gandi config --account accountname`

Pardon my ignorance if this is already possible somehow, but the docs don't seem to mention this.

**Comment by jake9050** [comment]
Nevermind..
The config command does what i need, a simple wrapper script around this is all i takes

**Comment by sayoun** [comment]
Hello,

you can use multiple accounts easily using shell environment variable and making shell aliases

using something like: `API_KEY=XXXXXXX gandi` allows you to use another apikey with gandicli, environment variables are always read before configuration file.

**Comment by jake9050** [comment]
Thank you sayoun.
