### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by ligne13** [Gandi/gandi.cli#176]
This issue follows the support ticket #6495916 created by Gandi support which is still not resolved.

I can't deploy my code on my new PHP 5.6 Simple Hosting instance. Neither the 'gandi deploy' command nor the 'ssh user@host deploy vhost.git' command work.

```
$ gandi deploy
Usage: gandi deploy [OPTIONS]

Error:  is not a valid Simple Hosting git remote
```

```
ssh user@git.dc0.gpaas.net 'deploy myvhost.git'
initializing builder
..................builder ready
Vm password: 
Grabbing terminal
Ok
-----> Starting new deployment (myvhost - master)
-----> Fetching application code
-----> Building new application
/srv/admin/build0/php5/install.sh: line 4: pushd: htdocs: No such file or directory
-----> Building new application failed
-----> Aborting deployment
```

Please provide a fix for this issue that make my Simple Hosting instance unusable.

**Comment by sayoun** [comment]
Hello @ligne13,

Which version of Gandi CLI are you using ?

Since the last version (0.17), `gandi deploy` command error happen when you're using it from a directory which is not a git repository so it cannot extract the remote url to use for ssh deploy command.

Please check that you are using it from a valid git repository.

**Comment by ligne13** [comment]
Hi,
I do call gandi deploy from a git repo. But I think the error happens because I don't have a htdocs directory. My public directort is named "public" as the Laravel default. I will try to rename the public dir to htdocs and will let you know.

**Comment by sayoun** [comment]
Well after some tests. `gandi deploy` command seems broken in 0.17 in some case. For now I'll suggest you to use the `ssh` manual command for now until we fix this (we have a PR currently under review for this bug).
