### ISSUE TITLE
Detect datacenter when creating a new disk

### ISSUE THREAD

**Issue by jbq** [Gandi/gandi.cli#182]
When creating a new disk without specifying the datacenter option, there can be an error like this one:

```
    $ gandi disk create --size=10G --vm srv1 --name docker_srv1
    Creating your disk.
    Progress: [##############################################################################################] 100.00%  00:00:34  
    Usage: gandi disk [OPTIONS]

    Error: Gandi API has returned an error: <Fault 530451: 'Error on object : OBJECT_DISK (CAUSE_DATACENTER) [VM and Disk must be in the same datacenter]'>
```

When the `--vm` option is specified, CLI could fetch the datacenter of the VM for disk creation, or a new option like `--detect-datacenter` could be added to request that the new disk be in the same DC as the VM.

To sum up, when I create a new disk with the `--vm` option I'd like it to be on the same datacenter than the VM.  This would be a time-saver.

**Comment by sayoun** [comment]
Will be available in next release
