### ISSUE TITLE
[Feature request] Limit option for records

### ISSUE THREAD

**Issue by SabakuRou** [Gandi/gandi.cli#187]
Hello,

Could you please add the --limit option for the record feature ?

$ gandi record list blabla.com --format text | wc -l
100

My record zone have 226 entries.

$ gandi record list --limit 300 --format text blabla.com
Error: no such option: --limit

Thanks you.
Jérémy

**Comment by sayoun** [comment]
Will be available in next release.

**Comment by SabakuRou** [comment]
Hello!
Thank you.
When will the next release come out ?

Cheers.
Jérémy

**Comment by sayoun** [comment]
Fixed in release 0.19
