### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by neeklamy** [Gandi/gandi.cli#188]
These links in the README.md Table of contents are broken:

- **Deploying a Web Application with Simple Hosting**  
`#deploying-a-web-application` should be:  
`#deploying-a-web-application-with-simple-hosting`
- **Development**  
is redundant here as it was moved to CONTRIBUTING: 7e81b7e20e826e191ed96db1326ded1b94dfa21c

**Comment by sayoun** [comment]
Thanks, this has been fixed in release 0.19
