### ISSUE TITLE
CLI not working on Windows

### ISSUE THREAD

**Issue by jhorchler** [Gandi/gandi.cli#190]
Even having Python available on Windows gandi.cli is not working on this platform.

The problem is that **gandi\cli\core\utils\unixpipe.py** is using `import posix`  which is just not available on Windows. The error stack trying `gandi setup` is: 

> Traceback (most recent call last):
>   File "C:\App\Python35\Scripts\gandi-script.py", line 9, in <module>
>     load_entry_point('gandi.cli==0.18', 'console_scripts', 'gandi')()
>   File "c:\app\python35\lib\site-packages\gandi\cli\__main__.py", line 8, in main
>     cli(obj={})
>   File "c:\app\python35\lib\site-packages\click\core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\app\python35\lib\site-packages\click\core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "c:\app\python35\lib\site-packages\gandi\cli\core\cli.py", line 220, in invoke
>     ctx.obj = GandiContextHelper(verbose=ctx.obj['verbose'])
>   File "c:\app\python35\lib\site-packages\gandi\cli\core\base.py", line 312, in __init__
>     self.load_modules()
>   File "c:\app\python35\lib\site-packages\gandi\cli\core\base.py", line 340, in load_modules
>     __import__(module_name, fromlist=[module_name])
>   File "c:\app\python35\lib\site-packages\gandi\cli\modules\docker.py", line 6, in <module>
>     from gandi.cli.core.utils import unixpipe
>   File "c:\app\python35\lib\site-packages\gandi\cli\core\utils\unixpipe.py", line 4, in <module>
>     import posix
> ImportError: No module named 'posix'

**Comment by sayoun** [comment]
Thanks, I'll see to make this import optionnal if not available on some OS

**Comment by kalou** [comment]
my bad, I like posix and it's not the right way to do that
we could import os instead and let it fail on fork

we could also deprecate the docker experiment, as it's pretty old and covered by a lot of other tools now

**Comment by sayoun** [comment]
It should work on windows now using the latest github repository code, can you confirm @jhorchler ?

**Comment by jhorchler** [comment]
I'm not sure. It complains about Module 'pwd' now. 
I installed the latest github code with python directly instead of using pip. Is there anything else I have to to?

**Comment by kalou** [comment]
can you try and comment out the import pwd from unixpipe.py, test again, and give us any remaining traceback ?
I don't really have a computer [nor windows] by hand immediately - i can test tomorrow otherwise.

**Comment by jhorchler** [comment]
Commenting out 'pwd' does resolve the error. I was able to run 'gandi setup' and got information using 'gandi account info'. I've not tested any other commands.

**Comment by kalou** [comment]
Thanks for your testing! Let us know if you encounter new issues.
