### ISSUE TITLE
CLI certificate info have limit 500 cert

### ISSUE THREAD

**Issue by Simakink** [Gandi/gandi.cli#192]
CLI certificate info have limit 500 cert
i'm have over 500 certificate, and gandi cli not work with this

**Comment by Simakink** [comment]
gandi.cli/gandi/cli/modules/cert.py
line 125
  for cert in cls.list({'status': ['pending', 'valid'], 'items_per_page': 500})]
items_per_page=500 limit to request over API

**Comment by sayoun** [comment]
Hello, thank you for this report.

The Gandi API requires a value to be provided to go above the default 100, but we cannot retrieve an unlimited number of items, I'll use a greater value than 500 as a fix.

How many certificates do you have ?

**Comment by Simakink** [comment]
~540
i try use  'items_per_page': 900, not work

**Comment by sayoun** [comment]
the API will limit to 500, a call like `cert.list(XXX, {'status': ['pending', 'valid'], 'items_per_page': 500, 'page': 1}` must work to retrieve the certs after the 500th first but I'll need to fix the CLI so we iterate over all the pages after we cannot request more than 500 at a time.

**Comment by Simakink** [comment]
now i use
        result1 = [(cert['id'], [cert['cn']] + cert['altnames'])
                  for cert in cls.list({'status': ['pending', 'valid'],
                          'items_per_page': 500 , 'page': 1})]
        result2 = [(cert['id'], [cert['cn']] + cert['altnames'])
                  for cert in cls.list({'status': ['pending', 'valid'],
                          'items_per_page': 500 , 'page': 0})]
        result = result1 + result2

 but it's bad .... need rewrite this function

**Comment by sayoun** [comment]
I'll see to fix this in the next release.

**Comment by Simakink** [comment]
need rewrite this for use 'cn' on api gandi cert.list()

**Comment by sayoun** [comment]
This should be fixed in the next CLI release, we will add a new APIv3 method to filter on CN directly

**Comment by sayoun** [comment]
This issue has been fixed, if you use the latest github code it should work now.
