### ISSUE TITLE
at gandi wiki , gandi cli bad syntax ?

### ISSUE THREAD

**Issue by jordila** [Gandi/gandi.cli#202]
As per ...

https://wiki.gandi.net/en/iaas/tutorials/migrate_vm_dc#step_4_-_create_a_new_disk

```
~# gandi disk create --datacenter LU --size 6G --name Ax-sysdisk --vm asterix
```

is suggested, leading to

```
Error: /!\ Datacenter LU is closed, please choose another datacenter.
```

shouldn't

```
--datacenter FR-SD2|US-BA1|LU-SD1

```

 be suggested in the wiki ?

**Comment by sayoun** [comment]
Thanks, wiki page has been updated.
