### ISSUE TITLE
[Feature request] Allow to create and manage a forward address with multiple desitinations

### ISSUE THREAD

**Issue by srvg** [Gandi/gandi.cli#203]
Right now, the cli option `gandi forward create some@address.example -d alias@mydomain.example` only allows to configure a single forward address.

Via the Gandi website it is however possible to add in multiple targets. The cli also allows to retrieve the current targets with the f`forward list` option, when multiple were configured.

This is a request to allow to create and manage a forward address with multiple desitinations.

**Comment by sayoun** [comment]
Hello,

the `-d` parameter for `gandi forward create` command can be used multiple times in the same command so it should work as you need.

**Comment by srvg** [comment]
Hi, thank you for your feedback.

Whilst the suggested solution works, it only works when *initially* creating the forward. Adding additional addresses later on is not possible without first deleting the forward and then re-creating it with all pre-existing addresses, and the new ones.

Would you reconsider this request? Thank you.

**Comment by sayoun** [comment]
Command `gandi forward update -a newemail` should add the new address without needing to delete the previous ones

**Comment by sayoun** [comment]
@srvg can you test the update command and see if it fix your issue ?

**Comment by srvg** [comment]
That totally works, seems I overlooked the update command, sorry about that! Thank you!
