### ISSUE TITLE
[Deploy] mkdir: cannot create directory '/dev/null': Not a directory

### ISSUE THREAD

**Issue by popod** [Gandi/gandi.cli#206]
When deploying my git to gandi with the cli: `deploy default.git` I have this logs

```
-----> Starting new deployment (default - master)
-----> Fetching application code
-----> Building new application
mkdir: cannot create directory '/dev/null': Not a directory
mkdir: cannot create directory '/dev/null': Not a directory
v6.9.1 is already installed.
Now using node v6.9.1 (npm v3.10.8)
```

How to correct my express app to not have this `mkdir: cannot create directory '/dev/null': Not a directory` error ?

**Comment by bapt** [comment]
Somehow your application is trying to run mkdir /dev/null. It cannot work. seems like you may have a typo in your package.json or alike. in the scripts section, probably a missing redirection '>'

**Comment by popod** [comment]
Thanks for reply.. My package.json typo is ok. This is a part of my package.json

```
"scripts": {
    "start": "node ./bin/www",
    "start-dev": "DEBUG=appName:* nodemon ./bin/www",
    "deploy": "ssh <user>@git.<location>.gpaas.net 'deploy default.git'"
  },
  "engines": {
    "node": "^6.9.0",
    "npm": "*"
  }
```
Is it because of the "deploy" script which is called when y deploy ?

**Comment by ziir** [comment]
Hello,

I can confirm this issue is not related to your code or package.json; we're investigating it now.
Though this adds noise to your deploy logs, your express application should run fine

We'll get back to you as soon as this is resolved
Thanks again for bringing this to our attention

**Comment by ziir** [comment]
We deployed a fix addressing this issue to production today, you shall have clean deploy logs from now on.

For future queries about the Gandi Simple Hosting product, please use either:
- our support contact form https://www.gandi.net/support/contact/
- #gandi IRC channel on freenode

Of course, you're welcome to submit Gandi CLI specific issues here

Thanks again
