### ISSUE TITLE
Support batch updates for DNS records

### ISSUE THREAD

**Issue by jsonn** [Gandi/gandi.cli#212]
Currently, changing DNS records requires creating a new zone version, changing the entry and activating the version It would be nice if the first and last part could be made optional, so that when updating multiple records (e.g. bulk update of IPv6 prefixes) only a single zone version is created.

**Comment by jeekajoo** [comment]
Hello,
It looks like it was possible to do that with API v4:
```
$ gandi record list example.com --format text > file.zone
$ gandi record update example.com -f file.zone
```
There is no equivalent stuff for v5 (livedns). So it makes it difficult to do config management.

Thanks
J.

**Comment by tschmit** [comment]
I just migrate from V4 to V5 and now

`>gandi record create myDomain.tld --name test --type TXT --value test`
results in:
`No zone records found, domain myDomaine.tld doesn't seems to be managed at Gandi.`

but
`>gandi domain list`
results in
`myDomain.tld`

So I can't anymore script zone editing, for let's encrypt for example.

**Comment by jeekajoo** [comment]
@tschmit to my understanding, you can only use 'dns' namespace with V5. 'record' namespace is for V4. 'dns' namespace is still very limited. And It appeared 20 days ago with release 1.0 (https://github.com/Gandi/gandi.cli/releases).

**Comment by jsonn** [comment]
You might also try something like https://gist.github.com/jsonn/80339e792e5ffb78d276ebc3152b8531. Just replace xxx in the APIKEY.

With the move to LiveDNS, I consider my original issue obsolete.

**Comment by jeekajoo** [comment]
Well, YOU consider this cli doesn't have to support batch updates anymore with LiveDNS? :thinking:

**Comment by jsonn** [comment]
Well, the main motivation for batch updates for me was to simplify cleaning old zones up. That's gone :) Any new form of batch updates will likely require API changes for LiveDNS anyway and that's a completely different beast.

**Comment by kalou** [comment]
Supporting zonefile import/exports on v5 should be easy - I've created a separate issue #227
