### ISSUE TITLE
Best way to upgrade the Gandi CLI tool

### ISSUE THREAD

**Issue by jlambe** [Gandi/gandi.cli#216]
Hello,

I'm currently on version `0.20` and I was wondering what would be the best way to upgrade the CLI tool. I can't find any documentation on this nor any command for the tool to self-update.

I'm used to the composer `self-upgrade` command and have no experience with Python and how to manage packages with `pip`. Is there a `pip` command perhaps to update the CLI tool?

Also, perhaps it might be useful to show the latest version of the tool on the website instead of searching after the latest release on the Github repository.

Thanks for your help.

**Comment by eppfel** [comment]
I'm on 0.19 and have exactly this problem, because I want to upgrade to 0.20.

**Comment by sayoun** [comment]
Hello, if you installed the CLI using pip, you can use `pip install gandi.cli -U` to upgrade the package.

**Comment by eppfel** [comment]
Thank you @sayoun I was not aware of that `upgrade` flag. This did it for me.
