### ISSUE TITLE
Execute a command after deployment

### ISSUE THREAD

**Issue by jlambe** [Gandi/gandi.cli#217]
Is there a way to trigger/execute a custom command when using the `gandi deploy` command?

When working with PHP instances, running `gandi deploy` does not run a `composer update` on the server. After each deploy, we have to call the `gandi paas console` in order to log in and run manually the `composer update` command.

I was thinking that it might be useful to specify a command to run when calling the deployment command. For example: `gandi deploy --cmd="/usr/bin/php composer.phar update"`

Is there such option? or something similar?

Thanks.

**Comment by fatih-acar** [comment]
Hello,

You may use command events as described here: https://getcomposer.org/doc/articles/scripts.md
Using the `pre-install-cmd` or `post-install-cmd`, you can run any command before and/or after a `gandi deploy` (it calls `composer install` internally).

**Comment by jlambe** [comment]
@fatih-acar that's strange because that's what I've read on the Gandi docs that it runs `composer install` but on my instances, if I make a `gandi deploy`, it doesn't run composer.

And when I ssh into the instance, there are no paths to a `composer` script into it so I had to manually track `composer.phar` with the project. Any other idea?

**Comment by fatih-acar** [comment]
@jlambe the `composer` script is indeed not present on the instance at runtime, it is present only when running the deploy process

`composer` runs if you have `composer.lock` and `composer.json` files outside of your `htdocs` directory

**Comment by sayoun** [comment]
No response, should be fine.
