### ISSUE TITLE
Usage with beta v5

### ISSUE THREAD

**Issue by noplanman** [Gandi/gandi.cli#218]
Hi, I'm having issues getting the CLI to work with the new Gandi v5 beta.

When I try to use the old API key from v4 it doesn't work any more. Seems like my account isn't linked with the key correctly any more.

When I try to use a new API key generated in the new v5 admin panel, assigning it with `gandi setup`, I always get the following message when trying to execute an operation:
`Invalid API key, please use 'gandi setup' command.`

Is the v5 just not supported properly yet? Or is the XMLRPC URL different and needs to be set specifically in the `config.yaml` file?

**Comment by sayoun** [comment]
Hi, Gandi v5 Beta is providing a REST interface, where API v4 is using XMLRPC so the current CLI version is not compatible to use both for now, but we will add support for LiveDNS v5 API is the next CLI release.

**Comment by noplanman** [comment]
@sayoun Thanks so much for your quick reply!

I'm looking forward to the next release :tada:

So as it is now, I can't use the CLI for either v4 or v5, right? Because my account has been upgraded (if that's the right term) to v5, so I can't log in to v4 with my credentials any more. Also the API key for v4 doesn't seem to be linked to my account any more.

Best to just wait?

**Comment by sayoun** [comment]
Hello,

V5 REST API is only available for DNS management for now. As all our products are not available on the new website yet, even if you have upgraded your account to v5, your v4 API key should still work.

Have you put your "new"/renewed v4 API key into the `gandi setup` command ? If that's the case and it still won't work, what's the error message ?

**Comment by noplanman** [comment]
@sayoun Thanks so much for your patience and your replies 😊 

Regarding v4 and gandi.cli:
1. Create new API key on Gandi.net (v4)
2. Run `gandi setup` and enter new API key, production.
3. Run `gandi account info` (I have credits, which I can see on the Gandi website)
    ```
    Error: It appears you haven't purchased any credits yet.
    Please visit https://www.gandi.net/credit/buy to learn more and buy credits.
    ```
4. Run `gandi record list <domain>` (Using a domain I have registered on Gandi, which I have also used successfully with the CLI in the past):
    ```
    No zone records found, domain tgbot.net doesn't seems to be managed at Gandi.
    ```

So I'm not sure where the problem is, but it seems like the API key isn't correctly linked to my account.

Is there another command I can try to get some useful info to debug this?
Am I doing something wrong here? 😕

**Comment by noplanman** [comment]
Update: Partly my bad regarding the `gandi record list <domain>` command, as I was pointing it to a domain that is now using the new v5 DNS system, which it shows as `External DNS` in my domains list.

For the ones that I haven't switched yet (which say `Gandi DNS`), the command works perfectly!

**Comment by hSATAC** [comment]
Looking forward to this.

I know it's hard to maintain a cli tool for both v4 & v5 but it feels like this tools is abandoned...

**Comment by noplanman** [comment]
@hSATAC I totally agree with you, but as soon as v5 is officially launched and most services updated, I'm pretty sure this project will get an awesome update too :tada:

**Comment by sayoun** [comment]
Hello, the latest 1.0 version includes a new `dns` namespace with commands to handle domains through LiveDNS (v5) API.
