### ISSUE TITLE
DeprecationWarning makes tests fail with python 3.6.2

### ISSUE THREAD

**Issue by rdoursenaud** [Gandi/gandi.cli#224]
In the 0.22 release.

There are `DeprecationWarning` in `test_vm.py` and `test_paas.py`.

The one in `test_paas.py` makes the tests fail.

Please see the attached log.

`python -V`
```
Python 3.6.2
```

[2017-09-14-makepkg.log.txt](https://github.com/Gandi/gandi.cli/files/1302300/2017-09-14-makepkg.log.txt)

**Comment by sayoun** [comment]
I pushed a fix to `test_paas.py` to avoid the warning, can you validate this using the latest master branch ?

**Comment by rdoursenaud** [comment]
Sorry for the late reply and thanks for the prompt fix!
I confirm this makes the tests pass.

Other warnings are now present in the code though.
See near the top of:
[2017-10-03-makepkg.log.txt](https://github.com/Gandi/gandi.cli/files/1353022/2017-10-03-makepkg.log.txt)

**Comment by sayoun** [comment]
I know but I'll not fix them, it's a warning on docstrings used in tests, it doesn't have any relation/impact with the working code.

**Comment by rdoursenaud** [comment]
No problem, just wanted to let you know ;)
Keep up the good work!
