### ISSUE TITLE
domain creation DomainExtraParameters

### ISSUE THREAD

**Issue by Maurozio** [Gandi/gandi.cli#225]
It seems that gandi cli can not register domains that require DomainExtraParameters http://doc.rpc.gandi.net/domain/reference.html#DomainExtraParameters

Can you help me with a temporary solution for using the domain extra parameters in gandi cli? For example "x-se_ident_number".
Unfortunately some domain extra parameters are mandatory for some TLDs.

in my opinion "--domain option is deprecated and will be removed upon next release." is not a good choice because using just one line to run a command is really very useful!

Thank you very much for your wonderful work on gandi cli!

**Comment by sayoun** [comment]
Hello,

the warning message is for the `--domain` parameter, you can still use one line to buy a domain by passing it directly as an argument.
```
gandi domain create --domain example.com
->
gandi domain create example.com
```

For the extra parameters we do not plan to add this for now, but feel free to make a PR to add this to the cli.

**Comment by grigouze** [comment]
I try to support it in #248

**Comment by grigouze** [comment]
@Maurozio It's now merged.

We will create a new release soon.
