### ISSUE TITLE
Support plain text zonefiles in dns

### ISSUE THREAD

**Issue by kalou** [Gandi/gandi.cli#227]
with {'Accept': 'text/plain'} headers, v5 API supports plaintext zonefiles on /records

It should not be too hard to support exporting/importing zonefiles from the CLI

**Comment by sayoun** [comment]
Hi,

you can already export in text using ``gandi dns list FQDN --text` but no import indeed.

**Comment by sayoun** [comment]
Release 1.1 added a `gandi dns update` command which support a `-f` parameter to provide a plaintext file, is it enough to close this issue ?

**Comment by kalou** [comment]
thanks!
