### ISSUE TITLE
Generate a user password at the creation of a VM

### ISSUE THREAD

**Issue by aegiap** [Gandi/gandi.cli#228]
With the 1.0 release, a VM creation has the `-login` and `--password` option to ask for the user password to setup in the VM. You cannot add a default password and username in the configuration file and I think this is a good practice. 

As I often spawn VM, waiting for the CLI to ask for a password and confirmation is a bit time consuming. I would like to have an option to get a random password generated locally by the CLI and printed at the end of the VM creation. The user would have to use a specific parameter in the command line. 

Something like:
```
$ gandi vm create --hostname myvm --user myuser --gen-password
[...]
Your Virtual Machine myvm has been created.
Your user myuser was setup with the password 4h$ChPhrttYksMa
Waiting for the vm to come online
[...]
```

**Comment by sayoun** [comment]
Fixed in release 1.1
