### ISSUE TITLE
SSH connect with ipv6 only and no ipv6 connectivity

### ISSUE THREAD

**Issue by romuald** [Gandi/gandi.cli#229]
When creating a new VM with ipv6 only connectivity, but from a connection without ipv6, the operation will fail after the global 5 minutes timeout.

We should try to detect if the ipv6 connectivity of the host running the client works at all.

Furthermore, when encountering this issue, it seems my computer did use 100% of one CPU (not tried to reproduce yet)

**Comment by sayoun** [comment]
This should be fixed in release 1.1
