### ISSUE TITLE
Create a new TXT record and update it

### ISSUE THREAD

**Issue by tristanbes** [Gandi/gandi.cli#232]
Hello,

We have a reseller account & we are planning to put our 4,000+ website on HTTPS with let's encrypt.
This will require a lot of DNS entry manipulation on our gandi account.

1. Can you post a valid example on how to create a new TXT entry for domain `example.com` please ?

2. When updating a DNS TXT entry, would it be possible to skip the current value of the entry ? It's bad because it forces us to know the previous value of the record

Ex, instead of:
```
gandi record update --record "_acme-challenge 10800 TXT \"<old_value>\"" --new-record "_acme-challenge 3600 TXT \"<new_value>\"" example.com
```
 We want to be able to do an **update by name of the key** like for example: 
```
gandi record update --record "_acme-challenge" "_acme-challenge 3600 TXT \"MLlKzzZBWF40xVxB-uRYMVwkl2UNAemmXnbMjNnsDaY\"" example.com
```

So in other terms
gandi record update --record "<key>" "<new value>" <domain>
or something similar that don't require us to know the previous value of this TXT key.

If not possible, how to retrieve this specific _acme-challenge entry so we can tell `gandi.cli` to update that record ?

Thanks.

**Comment by sayoun** [comment]
Hello @tristanbes, I've released the `gandi dns update` command if you want to use it for your massive update through LiveDNS

**Comment by tristanbes** [comment]
Also, we are stuck on v4 because of our reseller account so I cannot generate a REST api key.

**Comment by tristanbes** [comment]
> Another new feature on #gandiV5 is LiveDNS, our new DNS service. While our classic DNS service pushed zone file changes once every 20 minutes, the LiveDNS service does so immediately after each change. One word of warning, though: if you choose to change a domain’s DNS to LiveDNS, once you do so, zonefile records can no longer be managed on the v4 interface, unless you switch back to our classic DNS.

I'm afraid we can't use LiveDNS because : 
- Our customer service manages the DNS zone through your UI interface (It's unclear if you can manage LiveDNS zones through V5 UI or only vs API though)
- Our re-seller account can't use V5 of Gandi

**Comment by sayoun** [comment]
Ok, then I'll see if I can update the record update command to handle your use case without breaking anything.

**Comment by tristanbes** [comment]
great, thanks 👍

**Comment by sayoun** [comment]
@tristanbes I've released a new CLI version 1.2, the `gandi record update` command should now work if you only pass the name of the record

**Comment by tristanbes** [comment]
Would you mind post an example of the full working command please ? or add it into the readme ?

**Comment by sayoun** [comment]
Examples:

Create a new record entry:
```
gandi record create example.com --name _acme-challenge --ttl 3600 --type TXT --value BMLlKzzZBWF40xVxB-uRYMVwkl2UNAemmXnbMjNnsDaY
```
Update entry using only the record name:
```
$ gandi record update example.com --record '_acme-challenge' --new-record "_acme-challenge 3600 IN TXT uRYMVwkl2UNAemmXnbMjNnsDaY"
```
