### ISSUE TITLE
Attempt to clone simple hosting vhost returns 'Error: unkown identifier magento2'

### ISSUE THREAD

**Issue by JoshuaFlood** [Gandi/gandi.cli#235]
I've been attempting to follow the instructions here:

https://wiki.gandi.net/en/tutorials/simple/php/magento2

These instructions were originally posted for v4 and were migrated to v5 documentation when I asked whether they were still compatible, so perhaps the following issue is a result of the program being altered without docs being updated, though I feel that it is more likely a syntax error.

Running this command:

`$ gandi paas clone magento2 --vhost sub.domain.com (replacing sub.domain.com with the vhost name)`

I receive the following error response in the command line:

`Usage: gandi paas clone [OPTIONS] NAME`
`Error: unknown identifier magento2`

Thanks!

EDIT:

After exploring the CLI a little more, I have found that the attributed credentials are from my v4 account and not v5. Not sure if this is relevant.

**Comment by sayoun** [comment]
Hello,

do you see your instance `magento2` when you use `$ gandi paas list` command ? Is this an instance created on V5 website ?

If it's the case I'm sorry but the CLI handles only the LiveDNS part of V5 through the `$ gandi dns` namespace, all others namespaces will only work through the XML-RPC API as there is no public API available for V5 at the moment except LiveDNS.

**Comment by JoshuaFlood** [comment]
I don't see anything when I use the `$ gandi paas list` command.

The site in question is the default test vhost created in v5 when the simple hosting package was purchased, so should I assume that gandi does not use the LiveDNS service for its test sites?

**Comment by sayoun** [comment]
LiveDNS is only about managing DNS records, here you want to manipulate a PaaS instance, which was created on V5 website, the CLI does not handle that, you can only manipulate PaaS instances created on V4 website through the `$ gandi paas` commands.

**Comment by JoshuaFlood** [comment]
Ok thanks for the info.

FYI, when I first attempted to install magento the guidance in the Gandi documentation was missing for v5. When enquiring about how to implement it on v5, whoever I asked simply updated the v5 doc with the v4 guidance. Those instructions rely upon using the `$ gandi paas` command.

Obviously this is not a bug, or anything to do with your work here, but worth noting in case other people encounter similar problems.
