### ISSUE TITLE
certificate DCV challenge is wrong

### ISSUE THREAD

**Issue by yverry** [Gandi/gandi.cli#236]
Hi,

I've just order yesterday a DV SSL certificate via `gandi certificate create --csr my.csr --dcv-method dns -d 2 --type std` (with gandicli 1.0 -> i've just upgraded my gandicli to 1.2 AFTER).
The cli return the DNS record like:

`_024FEDD......99C221A378.domain 10800 IN CNAME 8FDDD891B7D.......84D3ECB65690FED801D1F272D3C5689.comodoca.com.`

Gandi website (v4) return to me another DNS record:

`_024FEDD......99C221A378.domain 10800 IN CNAME 8FDDD891B7D.......84D3ECB65690FED801D1F272D3C5689.2ce<extra string>2a47a2.comodoca.com.`

As you can see the webinterface add an extra string.
That mean CLI != webUI.

Regards,
Yann

**Comment by sayoun** [comment]
Hello @yverry thanks for the feedback, this should be fixed in the github master branch now thanks to  https://github.com/Gandi/gandi.cli/pull/237.

Can you retry using the latest github master branch code ?

**Comment by yverry** [comment]
Thank you! Impressive speed

I think to purchase a new x509 certificate next week, I'll keep you updated

**Comment by yverry** [comment]
Works nicely!
 thanks
