### ISSUE TITLE
unexpected keyword argument 'proxy_rdns'

### ISSUE THREAD

**Issue by pikurasa** [Gandi/gandi.cli#241]
May be related to https://github.com/Gandi/gandi.cli/issues/207

(04:14:55 PM) pikurasa: When I run the gandi script from python pip, I get this: `Error: An unknown error has occurred: create_connection() got an unexpected keyword argument 'proxy_rdns'`
(04:15:01 PM) pikurasa: Any ideas?
(04:15:40 PM) pikurasa: This script worked before. I suspect some change in how the python packages handle network proxies, but unsure...
(04:27:50 PM) Zakamiro: which gandi cli command are you using?
(04:31:17 PM) pikurasa: Gandi CLI 1.2 Zakamiro
(04:37:37 PM) Zakamiro: yeah that's the version i am using and i don't get that error
(04:38:04 PM) Zakamiro: is there a particular command that makes this error?
(04:43:00 PM) pikurasa: gandi paas list ... anything that connects to the Internet, I think
(04:45:52 PM) pikurasa: If I use youtube-dl, however, which I also installed via pip, it works fine...
(04:46:41 PM) pikurasa: I think it has something to do with changes in python-urllib3, if I were to guess...
(04:46:48 PM) muelli left the room (quit: Ping timeout: 256 seconds).
(04:46:51 PM) pikurasa: that has something about rdns
(04:49:41 PM) Zakamiro: hmm, i don't get that, have you already tried to uninstall and reinstall?
(04:50:14 PM) pikurasa: Zakamiro: yes...
(04:50:35 PM) pikurasa: I am tempted to uninstall and reinstall python-urllib3
(04:51:14 PM) Zakamiro: right, sadly the best I can suggest is to send us a support ticket
(04:51:22 PM) pikurasa: but, it seems connected to many other programs, so I would rather not. (I have already done a simple "remove", but did not yet do a "purge")
(04:52:09 PM) pikurasa: (I did take the gandi command completely off and then reinstall, however... same results)

What you should also know:
* My system's network is proxied through tor
* uname output is `4.4.0-112-generic #135+8.0trisquel1 SMP Tue Jan 23 14:54:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* There is a time I ran python pip as root (because that is what was recommended on a forum).I did uninstall all pip packages, purged pip, and then reinstalled *all* of my python programs (everything with "python" in the name), which seems to have remedied that issue.  (If this is the problem, please let me know what I might need to reinstall. Thanks!)
* Before this issue, I was getting the following problem:

<pre>
File "/home/me/.local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/socks.py", line 154, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:9050/
</pre>

I fixed that issue by doing this: `export all_proxy=socks5://127.0.0.1:9050/` (by specifying socks5) but now I get the `unexpected keyword argument 'proxy_rdns'` error.

**Comment by kalou** [comment]
Hi there,

I suspect a PySocks vs. urllib conflict - or something similar

Trying to reproduce your issue, I have no problem running the cli with:
urllib3==1.22
PySocks==1.6.8

Maybe the package providing your socks support needs an upgrade, too

You might want to try a clean virtualenv setup (try pipenv:
http://docs.python-guide.org/en/latest/dev/virtualenvs/)

**Comment by pikurasa** [comment]
> I suspect a PySocks vs. urllib conflict - or something similar

I think you are right.

I tried reinstalling all my python packages and it fixed a few things, but not all.

Bummer... That's I can say...

Closing this issue as I can see this is probably not an issue with the gandi script.

**Comment by pikurasa** [comment]
> You might want to try a clean virtualenv setup (try pipenv: http://docs.python-guide.org/en/latest/dev/virtualenvs/)

I tried this and am getting many other errors, so "bummer"!
