### ISSUE TITLE
Debian packaging: Please sign the releases

### ISSUE THREAD

**Issue by ge-fa** [Gandi/gandi.cli#242]
Hi,

This tool is about to be [packaged for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764342). As it deals with quite sensitive data, I would like to ensure, that the code, which is imported into Debian, wasn't tampered with along the way.

Therefore: Could you please sign the releases? See [this link](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) for some details how to do so.

Thanks for your work,
Georg

**Comment by grigouze** [comment]
Hello @ge-fa , i just sign the release 1.2 to test.

Is it ok for you ?

**Comment by grigouze** [comment]
I think it's ok.

I close the issue.
