### ISSUE TITLE
Distribute full source in source release tarball

### ISSUE THREAD

**Issue by bignose-debian** [Gandi/gandi.cli#243]
The [source releases at PyPI](https://pypi.org/project/gandi.cli/) contain instructions to build the manual page. These refer to ‘gandicli.man.rst’, a file that is not distributed with the source release.

There may be other generated files described in the instructions, that need source described not included in the source distribution.

Please ensure the source release tarball at PyPI contains the complete source for building all the generated files.

**Comment by aegiap** [comment]
AFAICT the source release 1.2 (latest available) contains the RestructuredText source text file to build the man page. See:
```
$ unzip -l gandi.cli-1.2.zip  | grep gandicli.man.rst
    52400  2018-01-16 16:28   gandi.cli-1.2/gandicli.man.rst
```

**Comment by aegiap** [comment]
This commit https://github.com/Gandi/gandi.cli/commit/90a095803b14426e1a4d20de7b53c0059e8c609a should fix the issue.
