### ISSUE TITLE
Support for domain.dnssec in XML-RPC API

### ISSUE THREAD

**Issue by Glandos** [Gandi/gandi.cli#245]
Currently, it seems that only the LiveDNS API (using REST) is supported to manage DNSSEC entries.

However, I have configured external DNS servers, and the only way to manage KSK is to use the web interface, or manual python script using the [DNSSEC API from XML-RPC](https://doc.rpc.gandi.net/domain/faq.html#dnssec) manually.
It is not really complicated, the API and the library is easy to manage, but I was just wondering if it was planned to integrate it in this client.

**Comment by grigouze** [comment]
I try to support it in #246

**Comment by grigouze** [comment]
@Glandos It's now merged in mster.

We will create a new version soon
