### ISSUE TITLE
Remove support for Python 3 earlier than 3.3

### ISSUE THREAD

**Issue by bignose-debian** [Gandi/gandi.cli#250]
The trove metadata declares Python 3 support only for versions 3.3 and later. There is still some code that makes allowances for Python 3 earlier versions; this code can be removed to simplify the combinations that can result.

**Comment by bignose-debian** [comment]
I have implemented a change to resolve this, in branch https://salsa.debian.org/bignose/gandi-cli/commits/wip/issue/github-250/remove-python3-earlier-than-3.3 in my personal fork repository.

**Comment by grigouze** [comment]
It's merged.

It will be included in the next release.
