### ISSUE TITLE
--port option for `vm ssh`

### ISSUE THREAD

**Issue by fspin** [Gandi/gandi.cli#274]
I have configured my ssh in a custom port, so I'm not able to connect with the gandi.cli into my vm, because there is no such option (I've tried `--port`, `-p` and `-P` after `ssh` and none of them will let me pass the port I'm using). I get always a connection refused 'cause it's trying to ssh throuhg the default port (22).

Is there something I'm missing? Or is there a reason why isn't possible to change the port in the command line?

**Comment by grigouze** [comment]
@fspin Maybe you miss the the argument "args" of vm ssh command :)

You can try something like "gandi vm ssh ID -- -p SSH_PORT"

**Comment by fspin** [comment]
how did I missed that! Thanks @grigouze!
