### ISSUE TITLE
Source errors in manual page

### ISSUE THREAD

**Issue by bignose-debian** [Gandi/gandi.cli#282]
The manual page document has some errors:

* Spelling and grammar errors in English text (discovered with a spell checker).
* Formatting mistakes in reStructuredText source (discovered by comparing the rendered output).

I will prepare a branch to correct these and follow up here.

**Comment by bignose-debian** [comment]
The branch [wip/issue/282/manpage-errors](https://salsa.debian.org/bignose/gandi-cli/tree/wip/issue/282/manpage-errors) in my personal fork repository now contains a set of commits to address this issue.

The branch currently merges cleanly to master (as of [commit 34f9382d9caedddf](https://github.com/Gandi/gandi.cli/commit/34f9382d9caedddf069ac4943e56e71801e7e045)).

**Comment by grigouze** [comment]
@bignose-debian Is it possible to create a pull request in github ?

Thanks for reporting errors

**Comment by bignose-debian** [comment]
I don't maintain repositories in GitHub, which isn't a problem because Git is distributed. You will be able to use Git to compare and merge from the other repository.

> Thanks for reporting errors

You're welcome, thank you for maintaining this tool!

**Comment by grigouze** [comment]
@bignose-debian PR created https://github.com/Gandi/gandi.cli/pull/284

**Comment by grigouze** [comment]
it's now merged in master

**Comment by bignose-debian** [comment]
> it's now merged in master

Thank you for the quick approval!
