### ISSUE TITLE
Deprecate tool if abandonned

### ISSUE THREAD

**Issue by axelsimon** [Gandi/gandi.cli#305]
Hello,

It appears this tool has been barely functional for several years now.
Currently (a pip install, which installs 1.5), running a simple `gandi api` returns:
```
Traceback (most recent call last):
  File "/home/axsimon/.local/lib/python3.8/site-packages/gandi/cli/core/utils/xmlrpc.py", line 51, in request
    resp.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.gandi.net/v5/
```

Furthermore, there are 29 issues open, some going back to 2014 and 2015, and 4 pull requests, some still mergeable going back to 2018.

There is also another tool on Pypi, simply named "[gandi](https://pypi.org/project/gandi/)" (a name which is likely problematic, trademark-wise), that has been updated in May 2020 (vs May 2019 for Gandi.cli)

If this tool will not be worked on anymore (it happens, that's ok), maybe it would be better to say so clearly and archive the repo?

**Comment by axelsimon** [comment]
Right, just saw that one hour ago (!) a 1.6 version was released. So the project is still active :)

**Comment by axelsimon** [comment]
I'm sorry to revisit this issue, but the tool is currently unusable: it actually *requires* two API keys, which the README doesn't even warn you about properly, and one of these two keys can only be obtained from https://v4.gandi.net/admin/api_key no longer exists.

It is therefore impossible to generate a working config for new users, making the tool useless.

Please consider adding a warning on the README warning users about this situation and/or deprecating the tool if no work is being done on it to maintain it

**Comment by duub** [comment]
and with the instructions in the readme i can not even install it...

**Comment by markvdb** [comment]
I've come to expect better from gandi than this. I wasted more than an hour of my time and had to come to the conclusion that gandi.cli is basicly abandonware . Gandi, please either label it as such or invest in it.

**Comment by InternetHoleOfStupidity** [comment]
Gandi could at least give us information about this issue.

As a paying customer who has a lot of domains, it really begins to be a pain in the *** to not be able to use the cli anymore.

I already migrated all my cloud instances to another provider as I found they were overpriced compared to others for the same level of performance and customer service.

I will soon do the same for my domains to finally be able to automate records management again

**Comment by yanndinendal** [comment]
This repo has been marked as deprecated in #313.

If gandi.cli worked for you it will continue to do so, otherwise we won't be able to maintain it; the hybrid approach between v3/v4 and v5 is not really maintainable, sorry.

As mentioned in #313, for now you can use the JSON REST APIs at https://api.gandi.net/docs/ (curl | jq is a good start); and the openstack cli for GandiCloud VPS.
