### ISSUE TITLE
change default settings behaviour

### ISSUE THREAD

**Issue by kalou** [Gandi/gandi.cli#54]
I really like the short form of vm create - especially for my quick-vm-needs.
however, I believe we should refine the default value overriding/saving methods.

My default datacenter is set to US for latency reasons. If I need a temporary LU vm, I'll use the --datacenter switch. I'll probably forget to switch it back to US the next time.

I'd suggest:
- continue saving a default value for some parameters when they do not have one
- stop overriding default values, if the customer uses a --switch it is probably an exception
- maybe adding a --save switch, or providing a more friendly gandi config command (especially to output current default values)

**Comment by aegiap** [comment]
I had the same problem with the --image param to gandi vm create. On the following call of the command, I wanted to use the default image I setup in my config file and removed the --image parameter. I was then a bit shocked to spawn a new virtual machine with the image of the previous call which was written in the config file.

+1 pour sayoun solution (only write in config file if this entry is not present)

Maybe futur templating could help solve this issue.

**Comment by soulshake** [comment]
I find the current behavior unexpected and disturbing as well.

Semi-related: thoughts on an (overrideable) confirmation prompt and/or an interactive option?

**Comment by ziir** [comment]
Fixed in #150, closing this.
