### ISSUE TITLE
gandi deploy causes unexpected git clone

### ISSUE THREAD

**Issue by soulshake** [Gandi/gandi.cli#68]
Running `gandi deploy` invokes a `git clone` of the vhost you're trying to deploy (if it's not initialized, at least).

**Comment by kalou** [comment]
ftr #106 is too old now, but I still consider this an issue

**Comment by stayhigh** [comment]
https://github.com/Gandi/gandi.cli#creating-a-ssl-certificate
Deploying a Web Application>
Update code and deploy>

**Comment by stayhigh** [comment]
https://github.com/Gandi/gandi.cli#creating-a-ssl-certificate
It is better to give some specified example to explain the command.
In the chapter of "Deploying a Web Application", the topic of "Update code and deploy"
There is two commands on it. Anyone have better example to share?
>git push gandi master
>gandi deploy

**Comment by webcracy** [comment]
Hi @stayhigh, I'm not sure I understood he question, could you please rephrase it?
