### ISSUE TITLE
Custom output for "info" commands

### ISSUE THREAD

**Issue by soulshake** [Gandi/gandi.cli#71]
This applies to all namespaces with some `info` command (`gandi vm info`, `gandi paas info`, etc).

It would be very useful if users could 1) **request only specific elements**, and/or 2) **get output in a structured format**.
### 1) request only specific elements

 Currently, I can only do this:

```
gandi paas info shine
name      : shine
type      : pythonmysql
size      : s
console   : 137512@console.dc1.gpaas.net
ftp_server: sftp.dc1.gpaas.net
git_server: git.dc1.gpaas.net
vhost     : f75eccb375.test-url.ws
vhost     : shine.soulshake.net
datacenter: US
```

and I would like to be able to do something like this:

```
$ gandi paas info shine --vhost
vhost     : f75eccb375.test-url.ws
vhost     : shine.soulshake.net
```
### 2) get output in a structured format:

Currently, the output of a `gandi vm info` command, for example:

```
$ gandi vm info irc
hostname      : irc
state         : running
cores         : 1
memory        : 256
console       : 1
datacenter    : US
bandwidth     : 102400.0
ip4           : 173.246.105.94
ip6           : 2604:3400:dc1:43:216:3eff:febb:3cc0

label         : Ubuntu 14.04 64 bits
kernel_version: 3.10-x86_64
name          : sys_irc
size          : 3072
```

If I want to use the CLI in my scripts, I currently need to do some `grep`/`cut`/`sed` acrobatics, e.g.:
    `$ gandi vm info $vm_hostname | grep ^ip4 | cut -d: -f2 | sed "s/^ //"`

It would be great if users could easily get this output into a Python dict (something like `gandi vm info irc --json`?), for example.

My dream is to be able to easily do things like this:

```
print(irc_info['ip4'])
173.246.105.94
```

**Comment by aegiap** [comment]
I agree with @sayoun : no need for filter of each element in the output. A simple use of grep/sed/awk/.. will to the trick.
