### ISSUE TITLE
Set a default path for git repos when a `git  clone` is made

### ISSUE THREAD

**Issue by AlxxxlA** [Gandi/gandi.cli#91]
Add a 'default_path' in the config.yaml to clone repository into the directory indicated. When I used `gandi vhost create` if you forgot to change directory, the folder is created in the current directory. I would like have a default path which all repository are clone to use this command and change directory automaticaly after that :

```
[12-01-15 - 6:25:24] [alex@badam] :/home/alex 
$ gandi vhost create --vhost courgette.bhz.im --paas test
Creating a new vhost.
Your vhost courgette.bhz.im has been created.
Your have set /home/alex/dev/paas/ as the default git directory, would you like to clone this vhost in this repo ? [y/N] y
Clonage dans '/home/alex/dev/paas/courgette.bhz.im'...
warning: Vous semblez avoir cloné un dépôt vide.
Vérification de la connectivité... fait.
[12-01-15 - 6:26:16] [alex@badam] :/home/alex/dev/paas.courgette.bhz.im/
$ 
```

**Comment by sayoun** [comment]
Fixed in release 0.17: paas and vhost namespaces have been updated and behavior changed
