### ISSUE TITLE
Acknowledge authors/contributors

### ISSUE THREAD

**Issue by soulshake** [Gandi/gandi.cli#93]
We don't currently acknowledge contributors to the Gandi CLI. We should.
We could do this automatically, see [node-contributors](https://github.com/xingrz/node-contributors) or [generate-authors.sh](https://github.com/docker/docker/blob/0722c9b536a6f9617f77090bfc78b9c583a1b8d1/project/generate-authors.sh), for example.

**Comment by webcracy** [comment]
@soulshake Maybe a link to https://github.com/Gandi/gandi.cli/graphs/contributors in the project's README would suffice ?

**Comment by sayoun** [comment]
I agree with @webcracy a simple link to the github graph will be enough

**Comment by aegiap** [comment]
Note that the link on github.com/../contributors only show the latest contributors in the project.

**Comment by sayoun** [comment]
@aegiap it shows all the commiters to the project since the beginning, it should be enough I think, it's not a clean list of names but it's automated.

**Comment by sayoun** [comment]
Closing this issue as I added the link in the README
see commiti: https://github.com/Gandi/gandi.cli/commit/6c528d5df0d418313670050bfa4fdbb257f9182d
